### ISSUE TITLE
Auto-detection of Max-X & Max-Y needs some workup

### ISSUE THREAD

**Issue by atultiwari** [lovasoa/dezoom.sh#4]
Hi,
I tried the updated version of script, ability to write custom image name, is really helpful. But, unfortunately auto-detection of Max-X (& Y) are not yet fully function. One out three tries it failed (other 2 were successful but can't trust it right now - reason in screenshot below)-
Screenshot of original image -
![screenshot 66](https://cloud.githubusercontent.com/assets/586934/21082260/18bde836-bffe-11e6-9bad-dd536c258e46.png)

While Screenshot of final image created by script -
![screenshot 67](https://cloud.githubusercontent.com/assets/586934/21082262/2e777c46-bffe-11e6-92fc-2d9ba18d27e6.png)

As you can see it's a partial image of original one and more importantly (for me) it missed the whole region which is the most important in this slide (circled in original image).

So for now, I will find max X & Y myself and will use script by providing these parameters.

Regards,

**Comment by lovasoa** [comment]
Automatic image size detection works by making requests of different tiles. If the request fails, then it considers that the tile doesn't exist, and that the image is smaller. So on a bad connection, a tile may fail to download, and make the script believe that the image is smaller where actually the problem comes from the connection.

The script has no way to distinguish the two cases (bad connection, or inexistent tile), except retrying download. But I disabled retries while determinating image size, because it makes the detection way slower.

**Comment by lovasoa** [comment]
I am going to add an option to enable download retries during image size detection.

**Comment by lovasoa** [comment]
Tile downloads are now retried even during size detection. That makes the process way slower (because a lot of tile fail to download), but more reliable.

Retries can be disabled with the new `-f` option,  that switches the behaviour back to *fast and less reliable*.
